[workspace]
members = [
    "crates/*",
]

resolver = "3"

[workspace.dependencies]
ndarray = "0.17.2"
dicom = "0.9.0"
nifti = {version = "0.17.0", features = ["nalgebra_affine"] }
serde = { version = "1.0", features = ["derive"] }
